### ISSUE TITLE
toDeepSignal throws an error when the state property can be null

### ISSUE THREAD

**Issue by sgomanf** [markostanimirovic/ngrx-signal-store-playground#3]
If we have a property of the state that can be null, and initialize to null, the toDeepSignal() function throws the following error:

core.mjs:10194 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'Symbol(SIGNAL)')
TypeError: Cannot read properties of null (reading 'Symbol(SIGNAL)')
    at Object.get (deep-signal.ts:14:28)
    at isSignal (core.mjs:2216:48)
    at rxMethodFn (rx-method.ts:63:17)

if we initialize the property with a value other than null it does not throw the error

**Comment by markostanimirovic** [comment]
Good catch @sgomanf! Let me know if you want to submit a PR for this.
